import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import JsxFeature from './ES6/JsxFeature';
import List from './Component/List';
import Message from './Component/Message';
import List2 from './Component/List2';
import Counter from './Component/Counter';
import CounterProps1 from './Component_Parent_Child/CounterProps1';
import CounterProps2 from './Component_Parent_Child/CounterProps2';
import CounterProps3 from './Component_Parent_Child/CounterProps3';
import ComponentState from './Component_Parent_Child/ComponentState';
import InputRefString from './Component_Parent_Child/InputRefString';
import InputRefFunction from './Component_Parent_Child/InputRefFunction';
import InputRefCreateRef from './Component_Parent_Child/InputRefCreateRef';
import Parent from './Component_Parent_Child/Parent';
import ParentTwo from './Component_Parent_Child/ParentTwo';
import CtrlStyle from './Component_Parent_Child_Deliver/CtrlStyle';
import Progress from './Component_Parent_Child_Deliver/Progress';
import HocAppOne from './ComponentHoc/HocAppOne';
import HocAppThree from './ComponentHocThree/HocAppThree';
import HocAppTwo from './ComponentHocTwo/HocAppTwo';
import ListRendering from './ListRendering/ListRendering';
import ArrayFunction from './ListRendering/ArrayFunction';
import FormText from './Form/FormText';
import RadioCheckbox from './Form/RadioCheckbox';
import FileUpload from './Form/FileUpload';
import SalesReport from './Homework/SalesReport';
import SalesReportLifeCycle from './Homework/SalesReportLifeCycle';
import QueryGoods from './Homework/QueryGoods';
import GoodsCreate from './Homework/GoodsCreate';
import GoodsReplenishment from './Homework/GoodsReplenishment';
import MemberLogin from './Homework/MemberLogin';
import Home from './Homework/Home';
import Cargood from './Homework/Cargood';
import Detail from './Homework/Detail';
// ReactDOM.render(<JsxFeature/>, d ocument.getElementById('root') );
// ReactDOM.render(<List/>, document.getElementById('root') );
// ReactDOM.render(<Message/>, document.getElementById('root') );
// ReactDOM.render(<List2/>, document.getElementById('root') );
// ReactDOM.render(<Counter/>, document.getElementById('root') );
// ReactDOM.render(<CounterProps1 initCount={16} />, document.getElementById('root') );
// ReactDOM.render(<CounterProps2/>, document.getElementById('root') );
// ReactDOM.render(<CounterProps3 initCount={'5'}/>, document.getElementById('root') );
// ReactDOM.render(<ComponentState initCount={'5'}/>, document.getElementById('root') );
// ReactDOM.render(<InputRefString/>, document.getElementById('root') );
// ReactDOM.render(<InputRefFunction/>, document.getElementById('root') );
// ReactDOM.render(<InputRefCreateRef/>, document.getElementById('root') );
// ReactDOM.render(<Parent/>, document.getElementById('root') );
// ReactDOM.render(<ParentTwo/>, document.getElementById('root') );
// ReactDOM.render(<CtrlStyle/>, document.getElementById('root') );
// ReactDOM.render(<Progress/>, document.getElementById('root') );
// ReactDOM.render(<HocAppOne/>, document.getElementById('root') );
// ReactDOM.render(<HocAppThree/>, document.getElementById('root') );
// ReactDOM.render(<HocAppTwo/>, document.getElementById('root') );
// ReactDOM.render(<ListRendering/>, document.getElementById('root') );
// ReactDOM.render(<ArrayFunction/>, document.getElementById('root') );
// ReactDOM.render(<FormText/>, document.getElementById('root') );
// ReactDOM.render(<RadioCheckbox/>, document.getElementById('root') );
// ReactDOM.render(<FileUpload/>, document.getElementById('root') );
// ReactDOM.render(<SalesReport/>, document.getElementById('root') );
// ReactDOM.render(<SalesReportLifeCycle/>, document.getElementById('root') );
// ReactDOM.render(<QueryGoods/>, document.getElementById('root') );
// ReactDOM.render(<GoodsCreate/>, document.getElementById('root') );
// ReactDOM.render(<GoodsReplenishment/>, document.getElementById('root') );
// ReactDOM.render(<MeberLogin/>, document.getElementById('root') );
ReactDOM.render(
  <BrowserRouter>
    <Home />
  </BrowserRouter>,
  document.getElementById('root'));